-- Generated by scripts/gen-seed.ts from src/data.ts. Demo rates: update them from the admin side before launch.
insert into public.card_brands (id, name, mono, color, ink, hot, min_value, max_value, sort) values
  ('apple', 'Apple / iTunes', 'A', '#1C1C1E', '#fff', true, 25, 2000, 0),
  ('amazon', 'Amazon', 'a', '#FF9900', '#161D26', true, 25, 1000, 1),
  ('steam', 'Steam', 'S', '#1B2838', '#66C0F4', true, 10, 500, 2),
  ('razer', 'Razer Gold', 'R', '#0B0B0B', '#44D62C', false, 10, 500, 3),
  ('googleplay', 'Google Play', 'G', '#E8F5EE', '#0B8043', false, 10, 500, 4),
  ('sephora', 'Sephora', 'Se', '#000000', '#fff', false, 25, 500, 5),
  ('nordstrom', 'Nordstrom', 'N', '#F2F0EB', '#1A1A1A', false, 25, 500, 6),
  ('ebay', 'eBay', 'e', '#FFFFFF', '#E53238', false, 25, 500, 7),
  ('vanilla', 'Vanilla Visa', 'V', '#F6E7C1', '#6B4E16', false, 25, 500, 8),
  ('walmart', 'Walmart', 'W', '#0071DC', '#FFC220', false, 25, 500, 9),
  ('xbox', 'Xbox', 'X', '#107C10', '#fff', false, 10, 500, 10),
  ('playstation', 'PlayStation', 'P', '#003791', '#fff', false, 10, 500, 11)
on conflict (id) do nothing;

insert into public.card_categories (id, brand_id, name, sort) values
  ('apple-100-500', 'apple', 'Apple $100–$500 (single card)', 0),
  ('apple-25-95', 'apple', 'Apple $25–$95', 1),
  ('apple-ecode', 'apple', 'Apple e-code (any value)', 2),
  ('amz-cash', 'amazon', 'Amazon cash receipt', 0),
  ('amz-noreceipt', 'amazon', 'Amazon no receipt', 1),
  ('amz-ecode', 'amazon', 'Amazon e-code', 2),
  ('steam-physical', 'steam', 'Steam physical', 0),
  ('steam-ecode', 'steam', 'Steam e-code', 1),
  ('razer-pin', 'razer', 'Razer Gold PIN', 0),
  ('gp-physical', 'googleplay', 'Google Play physical', 0),
  ('gp-ecode', 'googleplay', 'Google Play e-code', 1),
  ('seph', 'sephora', 'Sephora physical', 0),
  ('nord', 'nordstrom', 'Nordstrom physical', 0),
  ('ebay', 'ebay', 'eBay physical', 0),
  ('vanilla', 'vanilla', 'Vanilla one-time use', 0),
  ('vanilla-gift', 'vanilla', 'Vanilla gift card', 1),
  ('walmart', 'walmart', 'Walmart physical', 0),
  ('walmart-visa', 'walmart', 'Walmart Visa', 1),
  ('xbox', 'xbox', 'Xbox physical', 0),
  ('psn', 'playstation', 'PlayStation physical', 0)
on conflict (id) do nothing;

insert into public.card_rates (category_id, country, rate) values
  ('apple-100-500', 'US', 1190),
  ('apple-100-500', 'UK', 1420),
  ('apple-100-500', 'CA', 860),
  ('apple-100-500', 'AU', 790),
  ('apple-100-500', 'EU', 1260),
  ('apple-25-95', 'US', 1120),
  ('apple-25-95', 'UK', 1350),
  ('apple-25-95', 'CA', 820),
  ('apple-ecode', 'US', 1080),
  ('apple-ecode', 'UK', 1300),
  ('amz-cash', 'US', 1060),
  ('amz-cash', 'UK', 1270),
  ('amz-cash', 'CA', 760),
  ('amz-noreceipt', 'US', 960),
  ('amz-noreceipt', 'UK', 1150),
  ('amz-ecode', 'US', 900),
  ('steam-physical', 'US', 1150),
  ('steam-physical', 'UK', 1380),
  ('steam-physical', 'CA', 830),
  ('steam-physical', 'AU', 760),
  ('steam-physical', 'EU', 1230),
  ('steam-ecode', 'US', 1100),
  ('steam-ecode', 'UK', 1320),
  ('steam-ecode', 'EU', 1180),
  ('razer-pin', 'US', 1140),
  ('razer-pin', 'EU', 1210),
  ('gp-physical', 'US', 820),
  ('gp-physical', 'UK', 990),
  ('gp-ecode', 'US', 760),
  ('seph', 'US', 1010),
  ('seph', 'CA', 740),
  ('nord', 'US', 990),
  ('ebay', 'US', 930),
  ('ebay', 'UK', 1100),
  ('vanilla', 'US', 870),
  ('vanilla-gift', 'US', 820),
  ('walmart', 'US', 900),
  ('walmart-visa', 'US', 840),
  ('xbox', 'US', 880),
  ('xbox', 'UK', 1040),
  ('xbox', 'EU', 950),
  ('psn', 'US', 870),
  ('psn', 'UK', 1030)
on conflict do nothing;

insert into public.crypto_assets (id, symbol, name, color, network, buy_rate, sell_rate, deposit_address, min_amount, decimals, sort) values
  ('usdt', 'USDT', 'Tether', '#26A17B', 'TRC20 (Tron)', 1592, 1548, 'SET-YOUR-USDT-ADDRESS', 10, 2, 0),
  ('btc', 'BTC', 'Bitcoin', '#F7931A', 'Bitcoin', 171450000, 167200000, 'SET-YOUR-BTC-ADDRESS', 0.0005, 6, 1),
  ('eth', 'ETH', 'Ethereum', '#627EEA', 'ERC20 (Ethereum)', 6120000, 5960000, 'SET-YOUR-ETH-ADDRESS', 0.01, 4, 2),
  ('usdc', 'USDC', 'USD Coin', '#2775CA', 'BEP20 (BNB Chain)', 1588, 1542, 'SET-YOUR-USDC-ADDRESS', 10, 2, 3)
on conflict (id) do nothing;

insert into public.coupons (code, label, bonus_per_unit, first_sale_only) values
  ('YADEX10', '+₦10 per $1 on every card', 10, false),
  ('FIRSTSALE', '+₦25 per $1 on your first sale', 25, true)
on conflict (code) do nothing;
