// Writes supabase/seed.sql from the catalogue in src/data.ts so the app and database start with the same rates.
// Run: node --experimental-strip-types scripts/gen-seed.ts
// Deposit addresses are left as placeholders: put your real escrow wallet addresses in crypto_assets before taking crypto.
import { writeFileSync } from 'node:fs'
import { CARDS, COUPONS, CRYPTO } from '../src/data.ts'

const q = (v: string | number | boolean) => (typeof v === 'string' ? `'${v.replace(/'/g, "''")}'` : String(v))
const rows = (xs: (string | number | boolean)[][]) => xs.map(r => `  (${r.map(q).join(', ')})`).join(',\n')
const minOf = (symbol: string) => (symbol === 'BTC' ? 0.0005 : symbol === 'ETH' ? 0.01 : 10)

const sql = `-- Generated by scripts/gen-seed.ts from src/data.ts. Demo rates: update them from the admin side before launch.
insert into public.card_brands (id, name, mono, color, ink, hot, min_value, max_value, sort) values
${rows(CARDS.map((c, i) => [c.id, c.name, c.mono, c.color, c.ink, !!c.hot, c.min, c.max, i]))}
on conflict (id) do nothing;

insert into public.card_categories (id, brand_id, name, sort) values
${rows(CARDS.flatMap(c => c.categories.map((k, i) => [k.id, c.id, k.name, i])))}
on conflict (id) do nothing;

insert into public.card_rates (category_id, country, rate) values
${rows(CARDS.flatMap(c => c.categories.flatMap(k => Object.entries(k.rates).map(([cc, r]) => [k.id, cc, r as number]))))}
on conflict do nothing;

insert into public.crypto_assets (id, symbol, name, color, network, buy_rate, sell_rate, deposit_address, min_amount, decimals, sort) values
${rows(CRYPTO.map((a, i) => [a.id, a.symbol, a.name, a.color, a.network, a.buyRate, a.sellRate, `SET-YOUR-${a.symbol}-ADDRESS`, minOf(a.symbol), a.decimals, i]))}
on conflict (id) do nothing;

insert into public.coupons (code, label, bonus_per_unit, first_sale_only) values
${rows(Object.entries(COUPONS).map(([code, c]) => [code, c.label, c.bonusPerUnit, code === 'FIRSTSALE']))}
on conflict (code) do nothing;
`
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql)
console.log('wrote supabase/seed.sql')
